### ISSUE TITLE
Update Developer Guide to include proposed features

### ISSUE THREAD

**Issue by yeggasd** [CS2103JAN2018-W11-B4/main#44]
As mentioned by Joanne in the PR,
"IMPORTANT
I would want you to mention the following in your Developer guide

For each team member what are the features (major and minor) you are proposing?
1. Within the scope of the project, how does it fit in (just a one or 2 line summary)
2. Please do this by end of day Monday 19 March."

We would need to add our proposed feature and who would be doing them by **Monday 19 March**

**Comment by yeggasd** [comment]
#54  for my part

**Comment by jingyinno** [comment]
#60 #58 #57
